const ACTION = {
  PING: 'ACTION_PING',
  PONG: 'ACTION_PONG',
  MOVE: 'ACTION_MOVE',
  PEERS: 'ACTION_PEERS',
  PEER_SET_NAME: 'ACTION_PEER_SET_NAME',
  MESSAGE: 'ACTION_MESSAGE',
  NOTICE: 'ACTION_NOTICE',
  CONNECTION_CLOSED: 'ACTION_CONNECTION_CLOSED',
  SET_NAME: 'ACTION_SET_NAME',
  MUTE: 'ACTION_MUTE',
  ERROR: 'ACTION_ERROR',
  DISABLE_INPUT: 'ACTION_DISABLE_INPUT',
  ENABLE_INPUT: 'ACTION_ENABLE_INPUT'
};

export { ACTION };
