const ACTION = {
  CONNECTION_CLOSED: 'ACTION_CONNECTION_CLOSED',
  PING: 'ACTION_PING',
  PONG: 'ACTION_PONG',
  STATE: 'ACTION_STATE',
  STATE_REQUEST: 'ACTION_STATE_REQUEST',
  MOVE: 'ACTION_MOVE',
  MESSAGE: 'ACTION_MESSAGE',
  NOTICE: 'ACTION_NOTICE',
  MUTE: 'ACTION_MUTE',
  ERROR: 'ACTION_ERROR',
  PEERS: 'ACTION_PEERS',
  PEER_DISCONNECT: 'ACTION_PEER_DISCONNECT',
  SET_NAME: 'ACTION_SET_NAME'
};

export { ACTION };
